### ISSUE TITLE
Example can not be run

### ISSUE THREAD

**Issue by jackyluo-learning** [GreptimeTeam/greptimedb-client-java#9]
I have replaced the endpoint with my greptimeDB cluster, but failed to run Example.
The exception can be seen below:

Exception in thread "main" java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: failed to decode Protobuf message: InsertExpr.expr: ObjectExpr.expr: DatabaseRequest.exprs: BatchRequest.databases: invalid string value: data is not UTF-8 encoded
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at io.greptime.example.Example.runInsert(Example.java:111)
        at io.greptime.example.Example.main(Example.java:77)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: failed to decode Protobuf message: InsertExpr.expr: ObjectExpr.expr: DatabaseRequest.exprs: BatchRequest.databases: invalid string value: data is not UTF-8 encoded
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.greptime.rpc.interceptors.ClientRequestLimitInterceptor$1$1.onClose(ClientRequestLimitInterceptor.java:87)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:470)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:434)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:467)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)

**Comment by fengjiachun** [comment]
[Some refactor on  gRPC protocol](https://github.com/GreptimeTeam/greptimedb/commit/c5b0d2431f4095c7a429e84124a594e4fd56df78), I will fix it ASAP

**Comment by fengjiachun** [comment]
It is not a stable version yet as we are still working on the gRPC protocol refactoring.

**Comment by fengjiachun** [comment]
Fixed @jackyluo-learning

**Comment by jackyluo-learning** [comment]
> Fixed @jackyluo-learning

Hello, thanks. I have tried again today, but it still doesn't work and shown different exception message:

Exception in thread "main" java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: failed to decode Protobuf message: InsertExpr.expr: ObjectExpr.expr: DatabaseRequest.exprs: BatchRequest.databases: invalid wire type: Varint (expected LengthDelimited)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at io.greptime.example.Example.runInsert(Example.java:111)
        at io.greptime.example.Example.main(Example.java:77)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: failed to decode Protobuf message: InsertExpr.expr: ObjectExpr.expr: DatabaseRequest.exprs: BatchRequest.databases: invalid wire type: Varint (expected LengthDelimited)
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.greptime.rpc.interceptors.ClientRequestLimitInterceptor$1$1.onClose(ClientRequestLimitInterceptor.java:87)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:470)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:434)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:467)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        Suppressed: io.greptime.rpc.errors.OnlyErrorMessage: Grpc unary-call got an error, method=greptime.v1.Greptime/Batch, target=[1/172.21.8.20:30106], startCall=1669725051981, duration=2113 millis, ctx={retries=0, greptimedb.client.id=1, greptimedb.client.version=0.1.0}

**Comment by fengjiachun** [comment]
@jackyluo-learning 
Install the latest version of the greptimedb.

curl -L https://raw.githubusercontent.com/GreptimeTeam/greptimedb/develop/scripts/install.sh | sh

**Comment by jackyluo-learning** [comment]
> @jackyluo-learning Install the latest version of the greptimedb.
> 
> curl -L https://raw.githubusercontent.com/GreptimeTeam/greptimedb/develop/scripts/install.sh | sh

Thanks, I will have a try.
